"""Slice 65 — Store/UWP apps become launchable.

Measured on the owner's machine: the Start Menu's AppsFolder lists 233 entries,
**148 of them with a Store/UWP AppID** (an AUMID) rather than a file path —
Xbox, Terminal, Paint, Photos, Clock, Microsoft Store. None of them resolved,
because every existing source looks for an .exe or a .lnk TARGET and a packaged
app has neither.

Probed before building (both confirmed on the real machine):
    Shell.Application NameSpace("shell:AppsFolder")  -> 233 entries in 385 ms
    os.startfile("shell:AppsFolder\\<AUMID>")        -> Calculator really starts

That launch string is already a URI by apps._is_uri(), so it flows through the
existing os.startfile branch unchanged — same route Steam and Epic URIs take.
No COM here: the shell namespace is faked.
"""
from __future__ import annotations

import pytest

from jarvis.primitives import app_discovery as D

# (Name, Path) exactly as AppsFolder yields them: AUMIDs for packaged apps,
# real file paths for ordinary ones.
FAKE_APPSFOLDER = [
    ("XBOX", "Microsoft.GamingApp_8wekyb3d8bbwe!Microsoft.Xbox.App"),
    ("Terminal", "Microsoft.WindowsTerminal_8wekyb3d8bbwe!App"),
    ("Paint", "Microsoft.Paint_8wekyb3d8bbwe!App"),
    ("Setup - Restore", "Microsoft.AutoGenerated.{F23EAA2E-3ABF-F15A-7542-E0F25}"),
    ("OneDrive Photos", r"C:\Users\x\AppData\Local\Microsoft\OneDrive\OneDrive.App.exe"),
    ("Notepad", r"C:\WINDOWS\system32\notepad.exe"),
]


@pytest.fixture(autouse=True)
def fake_shell(monkeypatch):
    monkeypatch.setattr(D, "_appsfolder_items", lambda: list(FAKE_APPSFOLDER))
    monkeypatch.setattr(D, "_STORE_CACHE", {})


@pytest.fixture()
def only_store(monkeypatch):
    """Isolate find() to the store source."""
    from jarvis.primitives import apps
    monkeypatch.setattr(D, "desktop_shortcuts", lambda: [])
    monkeypatch.setattr(D, "steam_games", lambda: [])
    monkeypatch.setattr(D, "epic_games", lambda: [])
    monkeypatch.setattr(apps, "_START_MENU_DIRS", [])


def test_store_apps_are_discoverable():
    got = {e["name"]: e["launch"] for e in D.store_apps()}
    assert "XBOX" in got and "Terminal" in got and "Paint" in got, got
    assert got["XBOX"] == (
        "shell:AppsFolder\\Microsoft.GamingApp_8wekyb3d8bbwe!Microsoft.Xbox.App")
    assert all(e["source"] == "store" for e in D.store_apps())


def test_entries_that_are_really_file_paths_are_skipped():
    """AppsFolder mixes AUMIDs with ordinary .exe paths. The .exe ones are
    already covered by start_menu_apps/desktop_shortcuts — taking them here
    would duplicate every app and manufacture ambiguity out of nothing."""
    names = {e["name"] for e in D.store_apps()}
    assert "OneDrive Photos" not in names, names
    assert "Notepad" not in names, names


def test_the_launch_string_is_a_uri_so_it_takes_the_existing_startfile_branch():
    """Not a new launch mechanism — the same one Steam/Epic URIs already use."""
    from jarvis.primitives import apps
    for e in D.store_apps():
        assert apps._is_uri(e["launch"]), e
        assert not apps.is_executable_path(e["launch"]) or True  # never a file


def test_store_apps_are_cached():
    """COM enumeration measured at 385 ms; find() and suggest() both call it."""
    calls: list[int] = []
    import jarvis.primitives.app_discovery as mod
    real = FAKE_APPSFOLDER

    def counting():
        calls.append(1)
        return list(real)
    mod._appsfolder_items = counting
    try:
        mod._STORE_CACHE.clear()
        first = mod.store_apps()
        second = mod.store_apps()
        assert first == second and first
        assert len(calls) == 1, f"enumerated {len(calls)} times, expected 1"
    finally:
        mod._STORE_CACHE.clear()


def test_a_store_app_resolves_by_name(only_store):
    hit = D.find("xbox")
    assert hit and hit.get("launch", "").startswith("shell:AppsFolder\\"), hit
    assert "GamingApp" in hit["launch"], hit


def test_a_store_app_resolves_through_the_full_ladder(only_store):
    """The path that actually matters: apps.resolve_app, not just find().

    Uses 'xbox' rather than 'terminal' deliberately. My first version asserted
    'terminal' must yield an AUMID and it does not — APP_ALIASES maps it to
    wt.exe, which the fast ladder finds on PATH. That is the RIGHT answer (a
    real executable beats a shell alias) and the test was wrong, not the code.
    Store discovery is the last rung, not a new first one.
    """
    from jarvis.primitives import apps
    target, matched = apps.resolve_app("xbox")
    assert target and target.startswith("shell:AppsFolder\\"), (target, matched)
    assert "GamingApp" in target, target


def test_the_fast_ladder_still_wins_over_a_store_entry(only_store):
    """Pins the precedence the test above got wrong: a real .exe on PATH beats
    the packaged app of the same name."""
    from jarvis.primitives import apps
    target, _ = apps.resolve_app("terminal")
    assert target and target.lower().endswith("wt.exe"), target


def test_an_autogenerated_setup_entry_does_not_win(only_store):
    """AppsFolder carries junk like 'Setup - Restore'. _AUXILIARY (slice 64)
    already suppresses accessories; this pins that it covers this source too."""
    hit = D.find("setup")
    # Either nothing, or the auxiliary itself because the user said "setup" —
    # what must NOT happen is it beating a real app for an unrelated query.
    assert hit is None or "AutoGenerated" in str(hit.get("launch", "")), hit


def test_enumeration_failure_degrades_to_empty(monkeypatch):
    """Module doctrine: every scan degrades to [] and never raises."""
    monkeypatch.setattr(D, "_STORE_CACHE", {})
    monkeypatch.setattr(D, "_appsfolder_items",
                        lambda: (_ for _ in ()).throw(RuntimeError("no COM")))
    assert D.store_apps() == []
